"""Render the existing CV.tex content as a stable Jekyll CV page.

Only the CV's content sections are published; the private contact header and
LaTeX layout stay local. Unknown commands fail before the output is written.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def group(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise ValueError(f"Expected a braced argument near {text[start:start+50]!r}")
    depth = 1
    i = start + 1
    while i < len(text):
        if text[i] == "\\":
            i += 2
            continue
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
        i += 1
    raise ValueError("Unbalanced LaTeX braces")


def inline(text: str) -> str:
    out: list[str] = []
    i = 0
    while i < len(text):
        if text[i] != "\\":
            out.append(text[i])
            i += 1
            continue
        i += 1
        if i == len(text):
            raise ValueError("Trailing LaTeX escape")
        if text[i] in "%&_#{}$":
            out.append(text[i])
            i += 1
            continue
        if text[i] == " ":
            out.append(" ")
            i += 1
            continue
        m = re.match(r"[A-Za-z]+", text[i:])
        if not m:
            raise ValueError(f"Unsupported LaTeX near {text[i-1:i+25]!r}")
        cmd = m.group()
        i += len(cmd)
        if cmd in {"textbf", "textit", "emph", "uline"}:
            value, i = group(text, i)
            wrapped = inline(value)
            mark = "**" if cmd == "textbf" else "*" if cmd in {"textit", "emph"} else ""
            out.append(mark + wrapped + mark)
        elif cmd == "href":
            url, i = group(text, i)
            label, i = group(text, i)
            if not re.match(r"^(https?://|mailto:)", url):
                raise ValueError("Unsupported hyperlink scheme")
            out.append(f"[{inline(label)}]({url})")
        elif cmd == "hfill":
            out.append(" · ")
        elif cmd == "textbar":
            out.append(" | ")
        elif cmd == "mu":
            out.append("μ")
        elif cmd in {"noindent", "baselineskip"}:
            pass
        else:
            raise ValueError(f"Unsupported LaTeX command: \\{cmd}")
    result = "".join(out).replace("$μ$", "μ").replace("--", "–")
    # Do not silently publish unconverted math or raw HTML/Liquid.
    if "$" in result or "{{" in result or "{%" in result or re.search(r"<\s*[A-Za-z/!]", result):
        raise ValueError("Unsupported math, HTML, or Liquid in CV content")
    return re.sub(r"[ \t]+", " ", result).strip()


def render(source: str) -> str:
    first = source.find(r"\section*{")
    last = source.rfind(r"\end{document}")
    if first < 0 or last <= first:
        raise ValueError("Expected CV sections inside a LaTeX document")
    body = source[first:last]
    # The award entry uses tabularx only to right-align its year.
    body = re.sub(
        r"\\begin\{tabularx\}\{\\linewidth\}\{@\{\}Xr@\{\}\}(.*?)\\end\{tabularx\}",
        lambda m: m.group(1).replace(" & ", " · "), body, flags=re.S,
    )
    body = re.sub(r"\\Needspace\{[^{}]*\}", "", body)
    # Join physical source lines within a logical LaTeX paragraph/item.
    logical: list[str] = []
    pending = ""
    in_list = False
    for raw in body.splitlines():
        line = re.sub(r"(?<!\\)%.*$", "", raw).strip()
        if not line or line == r"\noindent":
            if pending:
                logical.append(pending)
                pending = ""
            logical.append("")
            continue
        if line in {r"\begin{itemize}", r"\end{itemize}"}:
            if pending:
                logical.append(pending)
                pending = ""
            logical.append("")
            in_list = line == r"\begin{itemize}"
            continue
        if line.startswith(r"\section*{") or line.startswith(r"\item "):
            if pending:
                logical.append(pending)
            pending = line
        elif pending and in_list:
            pending += " " + line
        else:
            if pending:
                logical.append(pending)
            pending = line
    if pending:
        logical.append(pending)

    lines = [
        "---", "permalink: /cv/", 'title: "Curriculum Vitae"',
        "author_profile: true", "---", "",
        "<!-- Generated by tools/render_web_cv.py from the local CV.tex. -->",
        "# Curriculum Vitae", "",
        "[Homepage]({{ '/' | relative_url }}) · "
        "[ORCID](https://orcid.org/0009-0004-1158-167X) · "
        "[GitHub](https://github.com/Zeming-Huang)", "",
    ]
    for line in logical:
        if not line:
            lines.append("")
            continue
        if line.startswith(r"\section*{"):
            heading, end = group(line, len(r"\section*"))
            if line[end:].strip():
                raise ValueError("Unexpected content after section heading")
            lines.extend(["", "## " + inline(heading), ""])
            continue
        prefix = "- " if line.startswith(r"\item ") else ""
        if prefix:
            line = line[len(r"\item "):]
        breaks = re.split(r"\\\\(?:\[[^\]]*\])?", line)
        # Explicit TeX line breaks become Markdown hard line breaks.
        trailing_break = len(breaks) > 1 and not breaks[-1]
        if trailing_break:
            breaks.pop()
        rendered = "  \n".join(inline(x) for x in breaks)
        if trailing_break:
            rendered += "  "
        lines.append(prefix + rendered)
    result = "\n".join(lines)
    return re.sub(r"\n{3,}", "\n\n", result).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, required=True)
    ap.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "_pages/cv.md")
    args = ap.parse_args()
    result = render(args.source.read_text(encoding="utf-8-sig"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(result, encoding="utf-8")
    print(f"Updated web CV: {args.output}")


if __name__ == "__main__":
    main()
